In [7]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.utils import shuffle

In [10]:
df= pd.read_csv("student-por.csv", sep=";")
df.head()

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...   
3     GP   F   15       U     GT3       T     4     2   health  services  ...   
4     GP   F   16       U     GT3       T     3     3    other     other  ...   

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0      4        3      4     1     1      3        4   0  11  11  
1      5        3      3     1     1      3        2   9  11  11  
2      4        3      2     2     3      3        6  12  13  12  
3      3        2      2     1     1      5        0  14  14  14  
4      4        3      2     1     2      5        0  11  13  13  

[5 rows x 33 columns]

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 649 entries, 0 to 648
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   school      649 non-null    object
 1   sex         649 non-null    object
 2   age         649 non-null    int64 
 3   address     649 non-null    object
 4   famsize     649 non-null    object
 5   Pstatus     649 non-null    object
 6   Medu        649 non-null    int64 
 7   Fedu        649 non-null    int64 
 8   Mjob        649 non-null    object
 9   Fjob        649 non-null    object
 10  reason      649 non-null    object
 11  guardian    649 non-null    object
 12  traveltime  649 non-null    int64 
 13  studytime   649 non-null    int64 
 14  failures    649 non-null    int64 
 15  schoolsup   649 non-null    object
 16  famsup      649 non-null    object
 17  paid        649 non-null    object
 18  activities  649 non-null    object
 19  nursery     649 non-null    object
 20  higher    

In [12]:
df = df[["G1", "G2", "G3", "studytime", "failures", "absences"]]
predict = "G3"


In [13]:
X = np.array(df.drop([predict], 1))
y = np.array(df[predict])


C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_13624\171201536.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  X = np.array(df.drop([predict], 1))


In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state= 101)


In [15]:
lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)
accuracy = lin_reg.score(X_test, y_test)
accuracy

0.9030577379076508

The linear regression model gave an accuracy of about 90% which is not bad in this task.

In [16]:
prediction = lin_reg.predict(X_test)
for i in range(len(prediction)):
    print(prediction[X], X_test[X], [y_test[X]])

[[ 9.26455661 14.53634572 18.58458526  9.26455661  8.74055866]
 [11.27846752 14.53634572 18.58458526  9.26455661 18.58458526]
 [ 9.41715854 10.29706891 18.58458526  9.26455661 12.3260583 ]
 ...
 [14.53634572  9.41715854 18.58458526  9.26455661 12.3260583 ]
 [11.41085186 11.41085186 11.76203029  9.26455661 12.3260583 ]
 [11.41085186 14.53634572 11.76203029  9.26455661  8.74055866]] [[[ 9  9  2  0  2]
  [14 14  1  0  7]
  [16 18  2  0 10]
  [ 9  9  2  0  2]
  [ 6  9  2  0  0]]

 [[11 11  2  0  0]
  [14 14  1  0  7]
  [16 18  2  0 10]
  [ 9  9  2  0  2]
  [16 18  2  0 10]]

 [[10  9  2  0  2]
  [11 10  1  0  0]
  [16 18  2  0 10]
  [ 9  9  2  0  2]
  [11 12  3  0  2]]

 ...

 [[14 14  1  0  7]
  [10  9  2  0  2]
  [16 18  2  0 10]
  [ 9  9  2  0  2]
  [11 12  3  0  2]]

 [[11 11  2  0  4]
  [11 11  2  0  4]
  [12 11  2  0 10]
  [ 9  9  2  0  2]
  [11 12  3  0  2]]

 [[11 11  2  0  4]
  [14 14  1  0  7]
  [12 11  2  0 10]
  [ 9  9  2  0  2]
  [ 6  9  2  0  0]]] [array([[ 9, 15, 18,  9, 11]